package com.kennysoft.mapper;

import com.kennysoft.model.ContentPublish;
import com.kennysoft.model.ContentPublishExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ContentPublishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_publish
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    long countByExample(ContentPublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_publish
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int deleteByExample(ContentPublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_publish
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_publish
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int insert(ContentPublish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_publish
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int insertSelective(ContentPublish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_publish
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    List<ContentPublish> selectByExampleWithRowbounds(ContentPublishExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_publish
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    List<ContentPublish> selectByExample(ContentPublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_publish
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") ContentPublish record, @Param("example") ContentPublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_publish
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByExample(@Param("record") ContentPublish record, @Param("example") ContentPublishExample example);
}