package com.kennysoft.mapper;

import com.kennysoft.model.ContentDown;
import com.kennysoft.model.ContentDownExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ContentDownMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_down
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    long countByExample(ContentDownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_down
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int deleteByExample(ContentDownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_down
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_down
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int insert(ContentDown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_down
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int insertSelective(ContentDown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_down
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    List<ContentDown> selectByExampleWithRowbounds(ContentDownExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_down
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    List<ContentDown> selectByExample(ContentDownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_down
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    ContentDown selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_down
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") ContentDown record, @Param("example") ContentDownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_down
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByExample(@Param("record") ContentDown record, @Param("example") ContentDownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_down
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByPrimaryKeySelective(ContentDown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_down
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByPrimaryKey(ContentDown record);
}