package com.kennysoft.mapper;

import com.kennysoft.model.ContentOrder;
import com.kennysoft.model.ContentOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ContentOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_order
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    long countByExample(ContentOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_order
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int deleteByExample(ContentOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_order
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_order
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int insert(ContentOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_order
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int insertSelective(ContentOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_order
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    List<ContentOrder> selectByExampleWithRowbounds(ContentOrderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_order
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    List<ContentOrder> selectByExample(ContentOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_order
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") ContentOrder record, @Param("example") ContentOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_order
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByExample(@Param("record") ContentOrder record, @Param("example") ContentOrderExample example);
}