package com.kennysoft.mapper;

import com.kennysoft.model.ContentOrigin;
import com.kennysoft.model.ContentOriginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ContentOriginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_origin
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    long countByExample(ContentOriginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_origin
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int deleteByExample(ContentOriginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_origin
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_origin
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int insert(ContentOrigin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_origin
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int insertSelective(ContentOrigin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_origin
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    List<ContentOrigin> selectByExampleWithRowbounds(ContentOriginExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_origin
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    List<ContentOrigin> selectByExample(ContentOriginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_origin
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") ContentOrigin record, @Param("example") ContentOriginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_origin
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByExample(@Param("record") ContentOrigin record, @Param("example") ContentOriginExample example);
}