package com.kennysoft.mapper;

import com.kennysoft.model.InjectionRequest;
import com.kennysoft.model.InjectionRequestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface InjectionRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table injection_request
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    long countByExample(InjectionRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table injection_request
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int deleteByExample(InjectionRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table injection_request
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table injection_request
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int insert(InjectionRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table injection_request
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int insertSelective(InjectionRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table injection_request
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    List<InjectionRequest> selectByExampleWithRowbounds(InjectionRequestExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table injection_request
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    List<InjectionRequest> selectByExample(InjectionRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table injection_request
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") InjectionRequest record, @Param("example") InjectionRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table injection_request
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByExample(@Param("record") InjectionRequest record, @Param("example") InjectionRequestExample example);
}