package com.kennysoft.mapper;

import com.kennysoft.model.KsRole;
import com.kennysoft.model.KsRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface KsRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    long countByExample(KsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int deleteByExample(KsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int insert(KsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int insertSelective(KsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    List<KsRole> selectByExampleWithRowbounds(KsRoleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    List<KsRole> selectByExample(KsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    KsRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") KsRole record, @Param("example") KsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByExample(@Param("record") KsRole record, @Param("example") KsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByPrimaryKeySelective(KsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByPrimaryKey(KsRole record);
}