package com.kennysoft.mapper;

import com.kennysoft.model.KsRole2admin;
import com.kennysoft.model.KsRole2adminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface KsRole2adminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role2admin
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    long countByExample(KsRole2adminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role2admin
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int deleteByExample(KsRole2adminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role2admin
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role2admin
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int insert(KsRole2admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role2admin
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int insertSelective(KsRole2admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role2admin
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    List<KsRole2admin> selectByExampleWithRowbounds(KsRole2adminExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role2admin
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    List<KsRole2admin> selectByExample(KsRole2adminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role2admin
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    KsRole2admin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role2admin
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") KsRole2admin record, @Param("example") KsRole2adminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role2admin
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByExample(@Param("record") KsRole2admin record, @Param("example") KsRole2adminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role2admin
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByPrimaryKeySelective(KsRole2admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role2admin
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByPrimaryKey(KsRole2admin record);
}