package com.kennysoft.mapper;

import com.kennysoft.model.KsRole2menu;
import com.kennysoft.model.KsRole2menuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface KsRole2menuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role2menu
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    long countByExample(KsRole2menuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role2menu
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int deleteByExample(KsRole2menuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role2menu
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role2menu
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int insert(KsRole2menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role2menu
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int insertSelective(KsRole2menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role2menu
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    List<KsRole2menu> selectByExampleWithRowbounds(KsRole2menuExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role2menu
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    List<KsRole2menu> selectByExample(KsRole2menuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role2menu
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    KsRole2menu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role2menu
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") KsRole2menu record, @Param("example") KsRole2menuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role2menu
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByExample(@Param("record") KsRole2menu record, @Param("example") KsRole2menuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role2menu
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByPrimaryKeySelective(KsRole2menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role2menu
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByPrimaryKey(KsRole2menu record);
}