package com.kennysoft.mapper;

import com.kennysoft.model.ObjMapping;
import com.kennysoft.model.ObjMappingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ObjMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_mapping
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    long countByExample(ObjMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_mapping
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int deleteByExample(ObjMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_mapping
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_mapping
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int insert(ObjMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_mapping
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int insertSelective(ObjMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_mapping
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    List<ObjMapping> selectByExampleWithRowbounds(ObjMappingExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_mapping
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    List<ObjMapping> selectByExample(ObjMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_mapping
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    ObjMapping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_mapping
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") ObjMapping record, @Param("example") ObjMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_mapping
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByExample(@Param("record") ObjMapping record, @Param("example") ObjMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_mapping
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByPrimaryKeySelective(ObjMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_mapping
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByPrimaryKey(ObjMapping record);
}