package com.kennysoft.mapper;

import com.kennysoft.model.PreferentinalAction;
import com.kennysoft.model.PreferentinalActionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PreferentinalActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preferentinal_action
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    long countByExample(PreferentinalActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preferentinal_action
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int deleteByExample(PreferentinalActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preferentinal_action
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preferentinal_action
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int insert(PreferentinalAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preferentinal_action
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int insertSelective(PreferentinalAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preferentinal_action
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    List<PreferentinalAction> selectByExampleWithRowbounds(PreferentinalActionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preferentinal_action
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    List<PreferentinalAction> selectByExample(PreferentinalActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preferentinal_action
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") PreferentinalAction record, @Param("example") PreferentinalActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preferentinal_action
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByExample(@Param("record") PreferentinalAction record, @Param("example") PreferentinalActionExample example);
}