package com.kennysoft.mapper;

import com.kennysoft.model.TvPlay;
import com.kennysoft.model.TvPlayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TvPlayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_play
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    long countByExample(TvPlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_play
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    int deleteByExample(TvPlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_play
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_play
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    int insert(TvPlay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_play
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    int insertSelective(TvPlay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_play
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    List<TvPlay> selectByExampleWithRowbounds(TvPlayExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_play
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    List<TvPlay> selectByExample(TvPlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_play
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    TvPlay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_play
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") TvPlay record, @Param("example") TvPlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_play
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    int updateByExample(@Param("record") TvPlay record, @Param("example") TvPlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_play
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    int updateByPrimaryKeySelective(TvPlay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_play
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    int updateByPrimaryKey(TvPlay record);
}