package com.kennysoft.mapper;

import com.kennysoft.model.WsLog;
import com.kennysoft.model.WsLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WsLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_log
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    long countByExample(WsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_log
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int deleteByExample(WsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_log
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_log
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int insert(WsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_log
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int insertSelective(WsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_log
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    List<WsLog> selectByExampleWithRowbounds(WsLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_log
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    List<WsLog> selectByExample(WsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_log
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") WsLog record, @Param("example") WsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ws_log
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    int updateByExample(@Param("record") WsLog record, @Param("example") WsLogExample example);
}