package com.kennysoft.model;

import java.io.Serializable;
import java.util.Date;

public class AdmAccount implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adm_account.id
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adm_account.account
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adm_account.password
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adm_account.name
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adm_account.phone
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adm_account.remark
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adm_account.fdate
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    private Date fdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table adm_account
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adm_account.id
     *
     * @return the value of adm_account.id
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adm_account.id
     *
     * @param id the value for adm_account.id
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adm_account.account
     *
     * @return the value of adm_account.account
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adm_account.account
     *
     * @param account the value for adm_account.account
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adm_account.password
     *
     * @return the value of adm_account.password
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adm_account.password
     *
     * @param password the value for adm_account.password
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adm_account.name
     *
     * @return the value of adm_account.name
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adm_account.name
     *
     * @param name the value for adm_account.name
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adm_account.phone
     *
     * @return the value of adm_account.phone
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adm_account.phone
     *
     * @param phone the value for adm_account.phone
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adm_account.remark
     *
     * @return the value of adm_account.remark
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adm_account.remark
     *
     * @param remark the value for adm_account.remark
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adm_account.fdate
     *
     * @return the value of adm_account.fdate
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    public Date getFdate() {
        return fdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adm_account.fdate
     *
     * @param fdate the value for adm_account.fdate
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    public void setFdate(Date fdate) {
        this.fdate = fdate;
    }
}