package com.kennysoft.model;

import java.io.Serializable;
import java.util.Date;

public class ContentDown implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_down.id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_down.ftitle
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String ftitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_down.fcontent
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String fcontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_down.fgroup
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String fgroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_down.ftype
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String ftype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_down.furl
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String furl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_down.fstatus
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String fstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_down.fdate
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private Date fdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_down.fdescription
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String fdescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table content_down
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_down.id
     *
     * @return the value of content_down.id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_down.id
     *
     * @param id the value for content_down.id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_down.ftitle
     *
     * @return the value of content_down.ftitle
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getFtitle() {
        return ftitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_down.ftitle
     *
     * @param ftitle the value for content_down.ftitle
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setFtitle(String ftitle) {
        this.ftitle = ftitle == null ? null : ftitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_down.fcontent
     *
     * @return the value of content_down.fcontent
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getFcontent() {
        return fcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_down.fcontent
     *
     * @param fcontent the value for content_down.fcontent
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setFcontent(String fcontent) {
        this.fcontent = fcontent == null ? null : fcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_down.fgroup
     *
     * @return the value of content_down.fgroup
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getFgroup() {
        return fgroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_down.fgroup
     *
     * @param fgroup the value for content_down.fgroup
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setFgroup(String fgroup) {
        this.fgroup = fgroup == null ? null : fgroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_down.ftype
     *
     * @return the value of content_down.ftype
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getFtype() {
        return ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_down.ftype
     *
     * @param ftype the value for content_down.ftype
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setFtype(String ftype) {
        this.ftype = ftype == null ? null : ftype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_down.furl
     *
     * @return the value of content_down.furl
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getFurl() {
        return furl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_down.furl
     *
     * @param furl the value for content_down.furl
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setFurl(String furl) {
        this.furl = furl == null ? null : furl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_down.fstatus
     *
     * @return the value of content_down.fstatus
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getFstatus() {
        return fstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_down.fstatus
     *
     * @param fstatus the value for content_down.fstatus
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setFstatus(String fstatus) {
        this.fstatus = fstatus == null ? null : fstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_down.fdate
     *
     * @return the value of content_down.fdate
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public Date getFdate() {
        return fdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_down.fdate
     *
     * @param fdate the value for content_down.fdate
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setFdate(Date fdate) {
        this.fdate = fdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_down.fdescription
     *
     * @return the value of content_down.fdescription
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getFdescription() {
        return fdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_down.fdescription
     *
     * @param fdescription the value for content_down.fdescription
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setFdescription(String fdescription) {
        this.fdescription = fdescription == null ? null : fdescription.trim();
    }
}