package com.kennysoft.model;

import java.io.Serializable;

public class KsAdmin implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_admin.id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_admin.ks_code
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String ksCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_admin.ks_login
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private Integer ksLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_admin.ks_password
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String ksPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ks_admin
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_admin.id
     *
     * @return the value of ks_admin.id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_admin.id
     *
     * @param id the value for ks_admin.id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_admin.ks_code
     *
     * @return the value of ks_admin.ks_code
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getKsCode() {
        return ksCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_admin.ks_code
     *
     * @param ksCode the value for ks_admin.ks_code
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setKsCode(String ksCode) {
        this.ksCode = ksCode == null ? null : ksCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_admin.ks_login
     *
     * @return the value of ks_admin.ks_login
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public Integer getKsLogin() {
        return ksLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_admin.ks_login
     *
     * @param ksLogin the value for ks_admin.ks_login
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setKsLogin(Integer ksLogin) {
        this.ksLogin = ksLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_admin.ks_password
     *
     * @return the value of ks_admin.ks_password
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getKsPassword() {
        return ksPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_admin.ks_password
     *
     * @param ksPassword the value for ks_admin.ks_password
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setKsPassword(String ksPassword) {
        this.ksPassword = ksPassword == null ? null : ksPassword.trim();
    }
}