package com.kennysoft.model;

import java.io.Serializable;

public class KsMenu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_menu.id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_menu.ks_code
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String ksCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_menu.ks_parent
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String ksParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_menu.ks_text
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String ksText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_menu.ks_value
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String ksValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_menu.ks_order
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private Integer ksOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_menu.ks_icon
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String ksIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_menu.ks_status
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private Integer ksStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ks_menu
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_menu.id
     *
     * @return the value of ks_menu.id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_menu.id
     *
     * @param id the value for ks_menu.id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_menu.ks_code
     *
     * @return the value of ks_menu.ks_code
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getKsCode() {
        return ksCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_menu.ks_code
     *
     * @param ksCode the value for ks_menu.ks_code
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setKsCode(String ksCode) {
        this.ksCode = ksCode == null ? null : ksCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_menu.ks_parent
     *
     * @return the value of ks_menu.ks_parent
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getKsParent() {
        return ksParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_menu.ks_parent
     *
     * @param ksParent the value for ks_menu.ks_parent
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setKsParent(String ksParent) {
        this.ksParent = ksParent == null ? null : ksParent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_menu.ks_text
     *
     * @return the value of ks_menu.ks_text
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getKsText() {
        return ksText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_menu.ks_text
     *
     * @param ksText the value for ks_menu.ks_text
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setKsText(String ksText) {
        this.ksText = ksText == null ? null : ksText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_menu.ks_value
     *
     * @return the value of ks_menu.ks_value
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getKsValue() {
        return ksValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_menu.ks_value
     *
     * @param ksValue the value for ks_menu.ks_value
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setKsValue(String ksValue) {
        this.ksValue = ksValue == null ? null : ksValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_menu.ks_order
     *
     * @return the value of ks_menu.ks_order
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public Integer getKsOrder() {
        return ksOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_menu.ks_order
     *
     * @param ksOrder the value for ks_menu.ks_order
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setKsOrder(Integer ksOrder) {
        this.ksOrder = ksOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_menu.ks_icon
     *
     * @return the value of ks_menu.ks_icon
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getKsIcon() {
        return ksIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_menu.ks_icon
     *
     * @param ksIcon the value for ks_menu.ks_icon
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setKsIcon(String ksIcon) {
        this.ksIcon = ksIcon == null ? null : ksIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_menu.ks_status
     *
     * @return the value of ks_menu.ks_status
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public Integer getKsStatus() {
        return ksStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_menu.ks_status
     *
     * @param ksStatus the value for ks_menu.ks_status
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setKsStatus(Integer ksStatus) {
        this.ksStatus = ksStatus;
    }
}