package com.kennysoft.model;

import java.io.Serializable;

public class KsRole2menu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_role2menu.id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_role2menu.ks_menu_code
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String ksMenuCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_role2menu.ks_role_code
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String ksRoleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ks_role2menu
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_role2menu.id
     *
     * @return the value of ks_role2menu.id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_role2menu.id
     *
     * @param id the value for ks_role2menu.id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_role2menu.ks_menu_code
     *
     * @return the value of ks_role2menu.ks_menu_code
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getKsMenuCode() {
        return ksMenuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_role2menu.ks_menu_code
     *
     * @param ksMenuCode the value for ks_role2menu.ks_menu_code
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setKsMenuCode(String ksMenuCode) {
        this.ksMenuCode = ksMenuCode == null ? null : ksMenuCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_role2menu.ks_role_code
     *
     * @return the value of ks_role2menu.ks_role_code
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getKsRoleCode() {
        return ksRoleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_role2menu.ks_role_code
     *
     * @param ksRoleCode the value for ks_role2menu.ks_role_code
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setKsRoleCode(String ksRoleCode) {
        this.ksRoleCode = ksRoleCode == null ? null : ksRoleCode.trim();
    }
}