package com.kennysoft.model;

import java.io.Serializable;

public class Logs implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.id
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.sql
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    private String sql;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table logs
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.id
     *
     * @return the value of logs.id
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.id
     *
     * @param id the value for logs.id
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.sql
     *
     * @return the value of logs.sql
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    public String getSql() {
        return sql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.sql
     *
     * @param sql the value for logs.sql
     *
     * @mbg.generated Thu Nov 22 17:38:07 CST 2018
     */
    public void setSql(String sql) {
        this.sql = sql == null ? null : sql.trim();
    }
}