package com.kennysoft.model;

import java.io.Serializable;

public class ObjMapping implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_mapping.id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_mapping.object_id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String objectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_mapping.action
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_mapping.parent_type
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String parentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_mapping.parent_id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_mapping.element_type
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String elementType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_mapping.element_id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String elementId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_mapping.element_code
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String elementCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_mapping.parent_code
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String parentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_mapping.property
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String property;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table obj_mapping
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_mapping.id
     *
     * @return the value of obj_mapping.id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_mapping.id
     *
     * @param id the value for obj_mapping.id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_mapping.object_id
     *
     * @return the value of obj_mapping.object_id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_mapping.object_id
     *
     * @param objectId the value for obj_mapping.object_id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setObjectId(String objectId) {
        this.objectId = objectId == null ? null : objectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_mapping.action
     *
     * @return the value of obj_mapping.action
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_mapping.action
     *
     * @param action the value for obj_mapping.action
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_mapping.parent_type
     *
     * @return the value of obj_mapping.parent_type
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getParentType() {
        return parentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_mapping.parent_type
     *
     * @param parentType the value for obj_mapping.parent_type
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setParentType(String parentType) {
        this.parentType = parentType == null ? null : parentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_mapping.parent_id
     *
     * @return the value of obj_mapping.parent_id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_mapping.parent_id
     *
     * @param parentId the value for obj_mapping.parent_id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_mapping.element_type
     *
     * @return the value of obj_mapping.element_type
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getElementType() {
        return elementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_mapping.element_type
     *
     * @param elementType the value for obj_mapping.element_type
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setElementType(String elementType) {
        this.elementType = elementType == null ? null : elementType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_mapping.element_id
     *
     * @return the value of obj_mapping.element_id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getElementId() {
        return elementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_mapping.element_id
     *
     * @param elementId the value for obj_mapping.element_id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setElementId(String elementId) {
        this.elementId = elementId == null ? null : elementId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_mapping.element_code
     *
     * @return the value of obj_mapping.element_code
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getElementCode() {
        return elementCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_mapping.element_code
     *
     * @param elementCode the value for obj_mapping.element_code
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setElementCode(String elementCode) {
        this.elementCode = elementCode == null ? null : elementCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_mapping.parent_code
     *
     * @return the value of obj_mapping.parent_code
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_mapping.parent_code
     *
     * @param parentCode the value for obj_mapping.parent_code
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_mapping.property
     *
     * @return the value of obj_mapping.property
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_mapping.property
     *
     * @param property the value for obj_mapping.property
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setProperty(String property) {
        this.property = property == null ? null : property.trim();
    }
}