package com.kennysoft.model;

import java.io.Serializable;

public class ObjObject implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_object.id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_object.object_type
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String objectType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_object.object_id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String objectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_object.action
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table obj_object
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_object.id
     *
     * @return the value of obj_object.id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_object.id
     *
     * @param id the value for obj_object.id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_object.object_type
     *
     * @return the value of obj_object.object_type
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getObjectType() {
        return objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_object.object_type
     *
     * @param objectType the value for obj_object.object_type
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setObjectType(String objectType) {
        this.objectType = objectType == null ? null : objectType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_object.object_id
     *
     * @return the value of obj_object.object_id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_object.object_id
     *
     * @param objectId the value for obj_object.object_id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setObjectId(String objectId) {
        this.objectId = objectId == null ? null : objectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_object.action
     *
     * @return the value of obj_object.action
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_object.action
     *
     * @param action the value for obj_object.action
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }
}