package com.kennysoft.model;

import java.util.ArrayList;
import java.util.List;

public class ObjSeriesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table obj_series
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table obj_series
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table obj_series
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_series
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public ObjSeriesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_series
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_series
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_series
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_series
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_series
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_series
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_series
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_series
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_series
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_series
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table obj_series
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andActorDisplayIsNull() {
            addCriterion("actor_display is null");
            return (Criteria) this;
        }

        public Criteria andActorDisplayIsNotNull() {
            addCriterion("actor_display is not null");
            return (Criteria) this;
        }

        public Criteria andActorDisplayEqualTo(String value) {
            addCriterion("actor_display =", value, "actorDisplay");
            return (Criteria) this;
        }

        public Criteria andActorDisplayNotEqualTo(String value) {
            addCriterion("actor_display <>", value, "actorDisplay");
            return (Criteria) this;
        }

        public Criteria andActorDisplayGreaterThan(String value) {
            addCriterion("actor_display >", value, "actorDisplay");
            return (Criteria) this;
        }

        public Criteria andActorDisplayGreaterThanOrEqualTo(String value) {
            addCriterion("actor_display >=", value, "actorDisplay");
            return (Criteria) this;
        }

        public Criteria andActorDisplayLessThan(String value) {
            addCriterion("actor_display <", value, "actorDisplay");
            return (Criteria) this;
        }

        public Criteria andActorDisplayLessThanOrEqualTo(String value) {
            addCriterion("actor_display <=", value, "actorDisplay");
            return (Criteria) this;
        }

        public Criteria andActorDisplayLike(String value) {
            addCriterion("actor_display like", value, "actorDisplay");
            return (Criteria) this;
        }

        public Criteria andActorDisplayNotLike(String value) {
            addCriterion("actor_display not like", value, "actorDisplay");
            return (Criteria) this;
        }

        public Criteria andActorDisplayIn(List<String> values) {
            addCriterion("actor_display in", values, "actorDisplay");
            return (Criteria) this;
        }

        public Criteria andActorDisplayNotIn(List<String> values) {
            addCriterion("actor_display not in", values, "actorDisplay");
            return (Criteria) this;
        }

        public Criteria andActorDisplayBetween(String value1, String value2) {
            addCriterion("actor_display between", value1, value2, "actorDisplay");
            return (Criteria) this;
        }

        public Criteria andActorDisplayNotBetween(String value1, String value2) {
            addCriterion("actor_display not between", value1, value2, "actorDisplay");
            return (Criteria) this;
        }

        public Criteria andDefinitionIsNull() {
            addCriterion("definition is null");
            return (Criteria) this;
        }

        public Criteria andDefinitionIsNotNull() {
            addCriterion("definition is not null");
            return (Criteria) this;
        }

        public Criteria andDefinitionEqualTo(String value) {
            addCriterion("definition =", value, "definition");
            return (Criteria) this;
        }

        public Criteria andDefinitionNotEqualTo(String value) {
            addCriterion("definition <>", value, "definition");
            return (Criteria) this;
        }

        public Criteria andDefinitionGreaterThan(String value) {
            addCriterion("definition >", value, "definition");
            return (Criteria) this;
        }

        public Criteria andDefinitionGreaterThanOrEqualTo(String value) {
            addCriterion("definition >=", value, "definition");
            return (Criteria) this;
        }

        public Criteria andDefinitionLessThan(String value) {
            addCriterion("definition <", value, "definition");
            return (Criteria) this;
        }

        public Criteria andDefinitionLessThanOrEqualTo(String value) {
            addCriterion("definition <=", value, "definition");
            return (Criteria) this;
        }

        public Criteria andDefinitionLike(String value) {
            addCriterion("definition like", value, "definition");
            return (Criteria) this;
        }

        public Criteria andDefinitionNotLike(String value) {
            addCriterion("definition not like", value, "definition");
            return (Criteria) this;
        }

        public Criteria andDefinitionIn(List<String> values) {
            addCriterion("definition in", values, "definition");
            return (Criteria) this;
        }

        public Criteria andDefinitionNotIn(List<String> values) {
            addCriterion("definition not in", values, "definition");
            return (Criteria) this;
        }

        public Criteria andDefinitionBetween(String value1, String value2) {
            addCriterion("definition between", value1, value2, "definition");
            return (Criteria) this;
        }

        public Criteria andDefinitionNotBetween(String value1, String value2) {
            addCriterion("definition not between", value1, value2, "definition");
            return (Criteria) this;
        }

        public Criteria andPictureRul1IsNull() {
            addCriterion("picture_rul1 is null");
            return (Criteria) this;
        }

        public Criteria andPictureRul1IsNotNull() {
            addCriterion("picture_rul1 is not null");
            return (Criteria) this;
        }

        public Criteria andPictureRul1EqualTo(String value) {
            addCriterion("picture_rul1 =", value, "pictureRul1");
            return (Criteria) this;
        }

        public Criteria andPictureRul1NotEqualTo(String value) {
            addCriterion("picture_rul1 <>", value, "pictureRul1");
            return (Criteria) this;
        }

        public Criteria andPictureRul1GreaterThan(String value) {
            addCriterion("picture_rul1 >", value, "pictureRul1");
            return (Criteria) this;
        }

        public Criteria andPictureRul1GreaterThanOrEqualTo(String value) {
            addCriterion("picture_rul1 >=", value, "pictureRul1");
            return (Criteria) this;
        }

        public Criteria andPictureRul1LessThan(String value) {
            addCriterion("picture_rul1 <", value, "pictureRul1");
            return (Criteria) this;
        }

        public Criteria andPictureRul1LessThanOrEqualTo(String value) {
            addCriterion("picture_rul1 <=", value, "pictureRul1");
            return (Criteria) this;
        }

        public Criteria andPictureRul1Like(String value) {
            addCriterion("picture_rul1 like", value, "pictureRul1");
            return (Criteria) this;
        }

        public Criteria andPictureRul1NotLike(String value) {
            addCriterion("picture_rul1 not like", value, "pictureRul1");
            return (Criteria) this;
        }

        public Criteria andPictureRul1In(List<String> values) {
            addCriterion("picture_rul1 in", values, "pictureRul1");
            return (Criteria) this;
        }

        public Criteria andPictureRul1NotIn(List<String> values) {
            addCriterion("picture_rul1 not in", values, "pictureRul1");
            return (Criteria) this;
        }

        public Criteria andPictureRul1Between(String value1, String value2) {
            addCriterion("picture_rul1 between", value1, value2, "pictureRul1");
            return (Criteria) this;
        }

        public Criteria andPictureRul1NotBetween(String value1, String value2) {
            addCriterion("picture_rul1 not between", value1, value2, "pictureRul1");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNull() {
            addCriterion("language is null");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNotNull() {
            addCriterion("language is not null");
            return (Criteria) this;
        }

        public Criteria andLanguageEqualTo(String value) {
            addCriterion("language =", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotEqualTo(String value) {
            addCriterion("language <>", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThan(String value) {
            addCriterion("language >", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThanOrEqualTo(String value) {
            addCriterion("language >=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThan(String value) {
            addCriterion("language <", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThanOrEqualTo(String value) {
            addCriterion("language <=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLike(String value) {
            addCriterion("language like", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotLike(String value) {
            addCriterion("language not like", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageIn(List<String> values) {
            addCriterion("language in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotIn(List<String> values) {
            addCriterion("language not in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageBetween(String value1, String value2) {
            addCriterion("language between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotBetween(String value1, String value2) {
            addCriterion("language not between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andWriterDisplayIsNull() {
            addCriterion("writer_display is null");
            return (Criteria) this;
        }

        public Criteria andWriterDisplayIsNotNull() {
            addCriterion("writer_display is not null");
            return (Criteria) this;
        }

        public Criteria andWriterDisplayEqualTo(String value) {
            addCriterion("writer_display =", value, "writerDisplay");
            return (Criteria) this;
        }

        public Criteria andWriterDisplayNotEqualTo(String value) {
            addCriterion("writer_display <>", value, "writerDisplay");
            return (Criteria) this;
        }

        public Criteria andWriterDisplayGreaterThan(String value) {
            addCriterion("writer_display >", value, "writerDisplay");
            return (Criteria) this;
        }

        public Criteria andWriterDisplayGreaterThanOrEqualTo(String value) {
            addCriterion("writer_display >=", value, "writerDisplay");
            return (Criteria) this;
        }

        public Criteria andWriterDisplayLessThan(String value) {
            addCriterion("writer_display <", value, "writerDisplay");
            return (Criteria) this;
        }

        public Criteria andWriterDisplayLessThanOrEqualTo(String value) {
            addCriterion("writer_display <=", value, "writerDisplay");
            return (Criteria) this;
        }

        public Criteria andWriterDisplayLike(String value) {
            addCriterion("writer_display like", value, "writerDisplay");
            return (Criteria) this;
        }

        public Criteria andWriterDisplayNotLike(String value) {
            addCriterion("writer_display not like", value, "writerDisplay");
            return (Criteria) this;
        }

        public Criteria andWriterDisplayIn(List<String> values) {
            addCriterion("writer_display in", values, "writerDisplay");
            return (Criteria) this;
        }

        public Criteria andWriterDisplayNotIn(List<String> values) {
            addCriterion("writer_display not in", values, "writerDisplay");
            return (Criteria) this;
        }

        public Criteria andWriterDisplayBetween(String value1, String value2) {
            addCriterion("writer_display between", value1, value2, "writerDisplay");
            return (Criteria) this;
        }

        public Criteria andWriterDisplayNotBetween(String value1, String value2) {
            addCriterion("writer_display not between", value1, value2, "writerDisplay");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andProgramTypeIsNull() {
            addCriterion("program_type is null");
            return (Criteria) this;
        }

        public Criteria andProgramTypeIsNotNull() {
            addCriterion("program_type is not null");
            return (Criteria) this;
        }

        public Criteria andProgramTypeEqualTo(String value) {
            addCriterion("program_type =", value, "programType");
            return (Criteria) this;
        }

        public Criteria andProgramTypeNotEqualTo(String value) {
            addCriterion("program_type <>", value, "programType");
            return (Criteria) this;
        }

        public Criteria andProgramTypeGreaterThan(String value) {
            addCriterion("program_type >", value, "programType");
            return (Criteria) this;
        }

        public Criteria andProgramTypeGreaterThanOrEqualTo(String value) {
            addCriterion("program_type >=", value, "programType");
            return (Criteria) this;
        }

        public Criteria andProgramTypeLessThan(String value) {
            addCriterion("program_type <", value, "programType");
            return (Criteria) this;
        }

        public Criteria andProgramTypeLessThanOrEqualTo(String value) {
            addCriterion("program_type <=", value, "programType");
            return (Criteria) this;
        }

        public Criteria andProgramTypeLike(String value) {
            addCriterion("program_type like", value, "programType");
            return (Criteria) this;
        }

        public Criteria andProgramTypeNotLike(String value) {
            addCriterion("program_type not like", value, "programType");
            return (Criteria) this;
        }

        public Criteria andProgramTypeIn(List<String> values) {
            addCriterion("program_type in", values, "programType");
            return (Criteria) this;
        }

        public Criteria andProgramTypeNotIn(List<String> values) {
            addCriterion("program_type not in", values, "programType");
            return (Criteria) this;
        }

        public Criteria andProgramTypeBetween(String value1, String value2) {
            addCriterion("program_type between", value1, value2, "programType");
            return (Criteria) this;
        }

        public Criteria andProgramTypeNotBetween(String value1, String value2) {
            addCriterion("program_type not between", value1, value2, "programType");
            return (Criteria) this;
        }

        public Criteria andProgramType2IsNull() {
            addCriterion("program_type2 is null");
            return (Criteria) this;
        }

        public Criteria andProgramType2IsNotNull() {
            addCriterion("program_type2 is not null");
            return (Criteria) this;
        }

        public Criteria andProgramType2EqualTo(String value) {
            addCriterion("program_type2 =", value, "programType2");
            return (Criteria) this;
        }

        public Criteria andProgramType2NotEqualTo(String value) {
            addCriterion("program_type2 <>", value, "programType2");
            return (Criteria) this;
        }

        public Criteria andProgramType2GreaterThan(String value) {
            addCriterion("program_type2 >", value, "programType2");
            return (Criteria) this;
        }

        public Criteria andProgramType2GreaterThanOrEqualTo(String value) {
            addCriterion("program_type2 >=", value, "programType2");
            return (Criteria) this;
        }

        public Criteria andProgramType2LessThan(String value) {
            addCriterion("program_type2 <", value, "programType2");
            return (Criteria) this;
        }

        public Criteria andProgramType2LessThanOrEqualTo(String value) {
            addCriterion("program_type2 <=", value, "programType2");
            return (Criteria) this;
        }

        public Criteria andProgramType2Like(String value) {
            addCriterion("program_type2 like", value, "programType2");
            return (Criteria) this;
        }

        public Criteria andProgramType2NotLike(String value) {
            addCriterion("program_type2 not like", value, "programType2");
            return (Criteria) this;
        }

        public Criteria andProgramType2In(List<String> values) {
            addCriterion("program_type2 in", values, "programType2");
            return (Criteria) this;
        }

        public Criteria andProgramType2NotIn(List<String> values) {
            addCriterion("program_type2 not in", values, "programType2");
            return (Criteria) this;
        }

        public Criteria andProgramType2Between(String value1, String value2) {
            addCriterion("program_type2 between", value1, value2, "programType2");
            return (Criteria) this;
        }

        public Criteria andProgramType2NotBetween(String value1, String value2) {
            addCriterion("program_type2 not between", value1, value2, "programType2");
            return (Criteria) this;
        }

        public Criteria andEnnameIsNull() {
            addCriterion("enname is null");
            return (Criteria) this;
        }

        public Criteria andEnnameIsNotNull() {
            addCriterion("enname is not null");
            return (Criteria) this;
        }

        public Criteria andEnnameEqualTo(String value) {
            addCriterion("enname =", value, "enname");
            return (Criteria) this;
        }

        public Criteria andEnnameNotEqualTo(String value) {
            addCriterion("enname <>", value, "enname");
            return (Criteria) this;
        }

        public Criteria andEnnameGreaterThan(String value) {
            addCriterion("enname >", value, "enname");
            return (Criteria) this;
        }

        public Criteria andEnnameGreaterThanOrEqualTo(String value) {
            addCriterion("enname >=", value, "enname");
            return (Criteria) this;
        }

        public Criteria andEnnameLessThan(String value) {
            addCriterion("enname <", value, "enname");
            return (Criteria) this;
        }

        public Criteria andEnnameLessThanOrEqualTo(String value) {
            addCriterion("enname <=", value, "enname");
            return (Criteria) this;
        }

        public Criteria andEnnameLike(String value) {
            addCriterion("enname like", value, "enname");
            return (Criteria) this;
        }

        public Criteria andEnnameNotLike(String value) {
            addCriterion("enname not like", value, "enname");
            return (Criteria) this;
        }

        public Criteria andEnnameIn(List<String> values) {
            addCriterion("enname in", values, "enname");
            return (Criteria) this;
        }

        public Criteria andEnnameNotIn(List<String> values) {
            addCriterion("enname not in", values, "enname");
            return (Criteria) this;
        }

        public Criteria andEnnameBetween(String value1, String value2) {
            addCriterion("enname between", value1, value2, "enname");
            return (Criteria) this;
        }

        public Criteria andEnnameNotBetween(String value1, String value2) {
            addCriterion("enname not between", value1, value2, "enname");
            return (Criteria) this;
        }

        public Criteria andReleaseYearIsNull() {
            addCriterion("release_year is null");
            return (Criteria) this;
        }

        public Criteria andReleaseYearIsNotNull() {
            addCriterion("release_year is not null");
            return (Criteria) this;
        }

        public Criteria andReleaseYearEqualTo(String value) {
            addCriterion("release_year =", value, "releaseYear");
            return (Criteria) this;
        }

        public Criteria andReleaseYearNotEqualTo(String value) {
            addCriterion("release_year <>", value, "releaseYear");
            return (Criteria) this;
        }

        public Criteria andReleaseYearGreaterThan(String value) {
            addCriterion("release_year >", value, "releaseYear");
            return (Criteria) this;
        }

        public Criteria andReleaseYearGreaterThanOrEqualTo(String value) {
            addCriterion("release_year >=", value, "releaseYear");
            return (Criteria) this;
        }

        public Criteria andReleaseYearLessThan(String value) {
            addCriterion("release_year <", value, "releaseYear");
            return (Criteria) this;
        }

        public Criteria andReleaseYearLessThanOrEqualTo(String value) {
            addCriterion("release_year <=", value, "releaseYear");
            return (Criteria) this;
        }

        public Criteria andReleaseYearLike(String value) {
            addCriterion("release_year like", value, "releaseYear");
            return (Criteria) this;
        }

        public Criteria andReleaseYearNotLike(String value) {
            addCriterion("release_year not like", value, "releaseYear");
            return (Criteria) this;
        }

        public Criteria andReleaseYearIn(List<String> values) {
            addCriterion("release_year in", values, "releaseYear");
            return (Criteria) this;
        }

        public Criteria andReleaseYearNotIn(List<String> values) {
            addCriterion("release_year not in", values, "releaseYear");
            return (Criteria) this;
        }

        public Criteria andReleaseYearBetween(String value1, String value2) {
            addCriterion("release_year between", value1, value2, "releaseYear");
            return (Criteria) this;
        }

        public Criteria andReleaseYearNotBetween(String value1, String value2) {
            addCriterion("release_year not between", value1, value2, "releaseYear");
            return (Criteria) this;
        }

        public Criteria andVolumnCountIsNull() {
            addCriterion("volumn_count is null");
            return (Criteria) this;
        }

        public Criteria andVolumnCountIsNotNull() {
            addCriterion("volumn_count is not null");
            return (Criteria) this;
        }

        public Criteria andVolumnCountEqualTo(String value) {
            addCriterion("volumn_count =", value, "volumnCount");
            return (Criteria) this;
        }

        public Criteria andVolumnCountNotEqualTo(String value) {
            addCriterion("volumn_count <>", value, "volumnCount");
            return (Criteria) this;
        }

        public Criteria andVolumnCountGreaterThan(String value) {
            addCriterion("volumn_count >", value, "volumnCount");
            return (Criteria) this;
        }

        public Criteria andVolumnCountGreaterThanOrEqualTo(String value) {
            addCriterion("volumn_count >=", value, "volumnCount");
            return (Criteria) this;
        }

        public Criteria andVolumnCountLessThan(String value) {
            addCriterion("volumn_count <", value, "volumnCount");
            return (Criteria) this;
        }

        public Criteria andVolumnCountLessThanOrEqualTo(String value) {
            addCriterion("volumn_count <=", value, "volumnCount");
            return (Criteria) this;
        }

        public Criteria andVolumnCountLike(String value) {
            addCriterion("volumn_count like", value, "volumnCount");
            return (Criteria) this;
        }

        public Criteria andVolumnCountNotLike(String value) {
            addCriterion("volumn_count not like", value, "volumnCount");
            return (Criteria) this;
        }

        public Criteria andVolumnCountIn(List<String> values) {
            addCriterion("volumn_count in", values, "volumnCount");
            return (Criteria) this;
        }

        public Criteria andVolumnCountNotIn(List<String> values) {
            addCriterion("volumn_count not in", values, "volumnCount");
            return (Criteria) this;
        }

        public Criteria andVolumnCountBetween(String value1, String value2) {
            addCriterion("volumn_count between", value1, value2, "volumnCount");
            return (Criteria) this;
        }

        public Criteria andVolumnCountNotBetween(String value1, String value2) {
            addCriterion("volumn_count not between", value1, value2, "volumnCount");
            return (Criteria) this;
        }

        public Criteria andOrgairDateIsNull() {
            addCriterion("orgair_date is null");
            return (Criteria) this;
        }

        public Criteria andOrgairDateIsNotNull() {
            addCriterion("orgair_date is not null");
            return (Criteria) this;
        }

        public Criteria andOrgairDateEqualTo(String value) {
            addCriterion("orgair_date =", value, "orgairDate");
            return (Criteria) this;
        }

        public Criteria andOrgairDateNotEqualTo(String value) {
            addCriterion("orgair_date <>", value, "orgairDate");
            return (Criteria) this;
        }

        public Criteria andOrgairDateGreaterThan(String value) {
            addCriterion("orgair_date >", value, "orgairDate");
            return (Criteria) this;
        }

        public Criteria andOrgairDateGreaterThanOrEqualTo(String value) {
            addCriterion("orgair_date >=", value, "orgairDate");
            return (Criteria) this;
        }

        public Criteria andOrgairDateLessThan(String value) {
            addCriterion("orgair_date <", value, "orgairDate");
            return (Criteria) this;
        }

        public Criteria andOrgairDateLessThanOrEqualTo(String value) {
            addCriterion("orgair_date <=", value, "orgairDate");
            return (Criteria) this;
        }

        public Criteria andOrgairDateLike(String value) {
            addCriterion("orgair_date like", value, "orgairDate");
            return (Criteria) this;
        }

        public Criteria andOrgairDateNotLike(String value) {
            addCriterion("orgair_date not like", value, "orgairDate");
            return (Criteria) this;
        }

        public Criteria andOrgairDateIn(List<String> values) {
            addCriterion("orgair_date in", values, "orgairDate");
            return (Criteria) this;
        }

        public Criteria andOrgairDateNotIn(List<String> values) {
            addCriterion("orgair_date not in", values, "orgairDate");
            return (Criteria) this;
        }

        public Criteria andOrgairDateBetween(String value1, String value2) {
            addCriterion("orgair_date between", value1, value2, "orgairDate");
            return (Criteria) this;
        }

        public Criteria andOrgairDateNotBetween(String value1, String value2) {
            addCriterion("orgair_date not between", value1, value2, "orgairDate");
            return (Criteria) this;
        }

        public Criteria andTagIsNull() {
            addCriterion("tag is null");
            return (Criteria) this;
        }

        public Criteria andTagIsNotNull() {
            addCriterion("tag is not null");
            return (Criteria) this;
        }

        public Criteria andTagEqualTo(String value) {
            addCriterion("tag =", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotEqualTo(String value) {
            addCriterion("tag <>", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagGreaterThan(String value) {
            addCriterion("tag >", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagGreaterThanOrEqualTo(String value) {
            addCriterion("tag >=", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagLessThan(String value) {
            addCriterion("tag <", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagLessThanOrEqualTo(String value) {
            addCriterion("tag <=", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagLike(String value) {
            addCriterion("tag like", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotLike(String value) {
            addCriterion("tag not like", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagIn(List<String> values) {
            addCriterion("tag in", values, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotIn(List<String> values) {
            addCriterion("tag not in", values, "tag");
            return (Criteria) this;
        }

        public Criteria andTagBetween(String value1, String value2) {
            addCriterion("tag between", value1, value2, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotBetween(String value1, String value2) {
            addCriterion("tag not between", value1, value2, "tag");
            return (Criteria) this;
        }

        public Criteria andOriginalCountryIsNull() {
            addCriterion("original_country is null");
            return (Criteria) this;
        }

        public Criteria andOriginalCountryIsNotNull() {
            addCriterion("original_country is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalCountryEqualTo(String value) {
            addCriterion("original_country =", value, "originalCountry");
            return (Criteria) this;
        }

        public Criteria andOriginalCountryNotEqualTo(String value) {
            addCriterion("original_country <>", value, "originalCountry");
            return (Criteria) this;
        }

        public Criteria andOriginalCountryGreaterThan(String value) {
            addCriterion("original_country >", value, "originalCountry");
            return (Criteria) this;
        }

        public Criteria andOriginalCountryGreaterThanOrEqualTo(String value) {
            addCriterion("original_country >=", value, "originalCountry");
            return (Criteria) this;
        }

        public Criteria andOriginalCountryLessThan(String value) {
            addCriterion("original_country <", value, "originalCountry");
            return (Criteria) this;
        }

        public Criteria andOriginalCountryLessThanOrEqualTo(String value) {
            addCriterion("original_country <=", value, "originalCountry");
            return (Criteria) this;
        }

        public Criteria andOriginalCountryLike(String value) {
            addCriterion("original_country like", value, "originalCountry");
            return (Criteria) this;
        }

        public Criteria andOriginalCountryNotLike(String value) {
            addCriterion("original_country not like", value, "originalCountry");
            return (Criteria) this;
        }

        public Criteria andOriginalCountryIn(List<String> values) {
            addCriterion("original_country in", values, "originalCountry");
            return (Criteria) this;
        }

        public Criteria andOriginalCountryNotIn(List<String> values) {
            addCriterion("original_country not in", values, "originalCountry");
            return (Criteria) this;
        }

        public Criteria andOriginalCountryBetween(String value1, String value2) {
            addCriterion("original_country between", value1, value2, "originalCountry");
            return (Criteria) this;
        }

        public Criteria andOriginalCountryNotBetween(String value1, String value2) {
            addCriterion("original_country not between", value1, value2, "originalCountry");
            return (Criteria) this;
        }

        public Criteria andIs3dIsNull() {
            addCriterion("is_3d is null");
            return (Criteria) this;
        }

        public Criteria andIs3dIsNotNull() {
            addCriterion("is_3d is not null");
            return (Criteria) this;
        }

        public Criteria andIs3dEqualTo(String value) {
            addCriterion("is_3d =", value, "is3d");
            return (Criteria) this;
        }

        public Criteria andIs3dNotEqualTo(String value) {
            addCriterion("is_3d <>", value, "is3d");
            return (Criteria) this;
        }

        public Criteria andIs3dGreaterThan(String value) {
            addCriterion("is_3d >", value, "is3d");
            return (Criteria) this;
        }

        public Criteria andIs3dGreaterThanOrEqualTo(String value) {
            addCriterion("is_3d >=", value, "is3d");
            return (Criteria) this;
        }

        public Criteria andIs3dLessThan(String value) {
            addCriterion("is_3d <", value, "is3d");
            return (Criteria) this;
        }

        public Criteria andIs3dLessThanOrEqualTo(String value) {
            addCriterion("is_3d <=", value, "is3d");
            return (Criteria) this;
        }

        public Criteria andIs3dLike(String value) {
            addCriterion("is_3d like", value, "is3d");
            return (Criteria) this;
        }

        public Criteria andIs3dNotLike(String value) {
            addCriterion("is_3d not like", value, "is3d");
            return (Criteria) this;
        }

        public Criteria andIs3dIn(List<String> values) {
            addCriterion("is_3d in", values, "is3d");
            return (Criteria) this;
        }

        public Criteria andIs3dNotIn(List<String> values) {
            addCriterion("is_3d not in", values, "is3d");
            return (Criteria) this;
        }

        public Criteria andIs3dBetween(String value1, String value2) {
            addCriterion("is_3d between", value1, value2, "is3d");
            return (Criteria) this;
        }

        public Criteria andIs3dNotBetween(String value1, String value2) {
            addCriterion("is_3d not between", value1, value2, "is3d");
            return (Criteria) this;
        }

        public Criteria andStarLevelIsNull() {
            addCriterion("star_level is null");
            return (Criteria) this;
        }

        public Criteria andStarLevelIsNotNull() {
            addCriterion("star_level is not null");
            return (Criteria) this;
        }

        public Criteria andStarLevelEqualTo(String value) {
            addCriterion("star_level =", value, "starLevel");
            return (Criteria) this;
        }

        public Criteria andStarLevelNotEqualTo(String value) {
            addCriterion("star_level <>", value, "starLevel");
            return (Criteria) this;
        }

        public Criteria andStarLevelGreaterThan(String value) {
            addCriterion("star_level >", value, "starLevel");
            return (Criteria) this;
        }

        public Criteria andStarLevelGreaterThanOrEqualTo(String value) {
            addCriterion("star_level >=", value, "starLevel");
            return (Criteria) this;
        }

        public Criteria andStarLevelLessThan(String value) {
            addCriterion("star_level <", value, "starLevel");
            return (Criteria) this;
        }

        public Criteria andStarLevelLessThanOrEqualTo(String value) {
            addCriterion("star_level <=", value, "starLevel");
            return (Criteria) this;
        }

        public Criteria andStarLevelLike(String value) {
            addCriterion("star_level like", value, "starLevel");
            return (Criteria) this;
        }

        public Criteria andStarLevelNotLike(String value) {
            addCriterion("star_level not like", value, "starLevel");
            return (Criteria) this;
        }

        public Criteria andStarLevelIn(List<String> values) {
            addCriterion("star_level in", values, "starLevel");
            return (Criteria) this;
        }

        public Criteria andStarLevelNotIn(List<String> values) {
            addCriterion("star_level not in", values, "starLevel");
            return (Criteria) this;
        }

        public Criteria andStarLevelBetween(String value1, String value2) {
            addCriterion("star_level between", value1, value2, "starLevel");
            return (Criteria) this;
        }

        public Criteria andStarLevelNotBetween(String value1, String value2) {
            addCriterion("star_level not between", value1, value2, "starLevel");
            return (Criteria) this;
        }

        public Criteria andIsChargeIsNull() {
            addCriterion("is_charge is null");
            return (Criteria) this;
        }

        public Criteria andIsChargeIsNotNull() {
            addCriterion("is_charge is not null");
            return (Criteria) this;
        }

        public Criteria andIsChargeEqualTo(String value) {
            addCriterion("is_charge =", value, "isCharge");
            return (Criteria) this;
        }

        public Criteria andIsChargeNotEqualTo(String value) {
            addCriterion("is_charge <>", value, "isCharge");
            return (Criteria) this;
        }

        public Criteria andIsChargeGreaterThan(String value) {
            addCriterion("is_charge >", value, "isCharge");
            return (Criteria) this;
        }

        public Criteria andIsChargeGreaterThanOrEqualTo(String value) {
            addCriterion("is_charge >=", value, "isCharge");
            return (Criteria) this;
        }

        public Criteria andIsChargeLessThan(String value) {
            addCriterion("is_charge <", value, "isCharge");
            return (Criteria) this;
        }

        public Criteria andIsChargeLessThanOrEqualTo(String value) {
            addCriterion("is_charge <=", value, "isCharge");
            return (Criteria) this;
        }

        public Criteria andIsChargeLike(String value) {
            addCriterion("is_charge like", value, "isCharge");
            return (Criteria) this;
        }

        public Criteria andIsChargeNotLike(String value) {
            addCriterion("is_charge not like", value, "isCharge");
            return (Criteria) this;
        }

        public Criteria andIsChargeIn(List<String> values) {
            addCriterion("is_charge in", values, "isCharge");
            return (Criteria) this;
        }

        public Criteria andIsChargeNotIn(List<String> values) {
            addCriterion("is_charge not in", values, "isCharge");
            return (Criteria) this;
        }

        public Criteria andIsChargeBetween(String value1, String value2) {
            addCriterion("is_charge between", value1, value2, "isCharge");
            return (Criteria) this;
        }

        public Criteria andIsChargeNotBetween(String value1, String value2) {
            addCriterion("is_charge not between", value1, value2, "isCharge");
            return (Criteria) this;
        }

        public Criteria andChareDescIsNull() {
            addCriterion("chare_desc is null");
            return (Criteria) this;
        }

        public Criteria andChareDescIsNotNull() {
            addCriterion("chare_desc is not null");
            return (Criteria) this;
        }

        public Criteria andChareDescEqualTo(String value) {
            addCriterion("chare_desc =", value, "chareDesc");
            return (Criteria) this;
        }

        public Criteria andChareDescNotEqualTo(String value) {
            addCriterion("chare_desc <>", value, "chareDesc");
            return (Criteria) this;
        }

        public Criteria andChareDescGreaterThan(String value) {
            addCriterion("chare_desc >", value, "chareDesc");
            return (Criteria) this;
        }

        public Criteria andChareDescGreaterThanOrEqualTo(String value) {
            addCriterion("chare_desc >=", value, "chareDesc");
            return (Criteria) this;
        }

        public Criteria andChareDescLessThan(String value) {
            addCriterion("chare_desc <", value, "chareDesc");
            return (Criteria) this;
        }

        public Criteria andChareDescLessThanOrEqualTo(String value) {
            addCriterion("chare_desc <=", value, "chareDesc");
            return (Criteria) this;
        }

        public Criteria andChareDescLike(String value) {
            addCriterion("chare_desc like", value, "chareDesc");
            return (Criteria) this;
        }

        public Criteria andChareDescNotLike(String value) {
            addCriterion("chare_desc not like", value, "chareDesc");
            return (Criteria) this;
        }

        public Criteria andChareDescIn(List<String> values) {
            addCriterion("chare_desc in", values, "chareDesc");
            return (Criteria) this;
        }

        public Criteria andChareDescNotIn(List<String> values) {
            addCriterion("chare_desc not in", values, "chareDesc");
            return (Criteria) this;
        }

        public Criteria andChareDescBetween(String value1, String value2) {
            addCriterion("chare_desc between", value1, value2, "chareDesc");
            return (Criteria) this;
        }

        public Criteria andChareDescNotBetween(String value1, String value2) {
            addCriterion("chare_desc not between", value1, value2, "chareDesc");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("score is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("score is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(String value) {
            addCriterion("score =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(String value) {
            addCriterion("score <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(String value) {
            addCriterion("score >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(String value) {
            addCriterion("score >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(String value) {
            addCriterion("score <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(String value) {
            addCriterion("score <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLike(String value) {
            addCriterion("score like", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotLike(String value) {
            addCriterion("score not like", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<String> values) {
            addCriterion("score in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<String> values) {
            addCriterion("score not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(String value1, String value2) {
            addCriterion("score between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(String value1, String value2) {
            addCriterion("score not between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andTimeLengthIsNull() {
            addCriterion("time_length is null");
            return (Criteria) this;
        }

        public Criteria andTimeLengthIsNotNull() {
            addCriterion("time_length is not null");
            return (Criteria) this;
        }

        public Criteria andTimeLengthEqualTo(String value) {
            addCriterion("time_length =", value, "timeLength");
            return (Criteria) this;
        }

        public Criteria andTimeLengthNotEqualTo(String value) {
            addCriterion("time_length <>", value, "timeLength");
            return (Criteria) this;
        }

        public Criteria andTimeLengthGreaterThan(String value) {
            addCriterion("time_length >", value, "timeLength");
            return (Criteria) this;
        }

        public Criteria andTimeLengthGreaterThanOrEqualTo(String value) {
            addCriterion("time_length >=", value, "timeLength");
            return (Criteria) this;
        }

        public Criteria andTimeLengthLessThan(String value) {
            addCriterion("time_length <", value, "timeLength");
            return (Criteria) this;
        }

        public Criteria andTimeLengthLessThanOrEqualTo(String value) {
            addCriterion("time_length <=", value, "timeLength");
            return (Criteria) this;
        }

        public Criteria andTimeLengthLike(String value) {
            addCriterion("time_length like", value, "timeLength");
            return (Criteria) this;
        }

        public Criteria andTimeLengthNotLike(String value) {
            addCriterion("time_length not like", value, "timeLength");
            return (Criteria) this;
        }

        public Criteria andTimeLengthIn(List<String> values) {
            addCriterion("time_length in", values, "timeLength");
            return (Criteria) this;
        }

        public Criteria andTimeLengthNotIn(List<String> values) {
            addCriterion("time_length not in", values, "timeLength");
            return (Criteria) this;
        }

        public Criteria andTimeLengthBetween(String value1, String value2) {
            addCriterion("time_length between", value1, value2, "timeLength");
            return (Criteria) this;
        }

        public Criteria andTimeLengthNotBetween(String value1, String value2) {
            addCriterion("time_length not between", value1, value2, "timeLength");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table obj_series
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 13 15:19:45 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table obj_series
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}