package com.kennysoft.model;

import java.io.Serializable;

public class ObjSeries implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_series.id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_series.actor_display
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String actorDisplay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_series.definition
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String definition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_series.picture_rul1
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String pictureRul1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_series.name
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_series.language
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_series.writer_display
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String writerDisplay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_series.description
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_series.program_type
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String programType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_series.program_type2
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String programType2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_series.enname
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String enname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_series.release_year
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String releaseYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_series.volumn_count
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String volumnCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_series.orgair_date
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String orgairDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_series.tag
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_series.original_country
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String originalCountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_series.is_3d
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String is3d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_series.star_level
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String starLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_series.is_charge
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String isCharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_series.chare_desc
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String chareDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_series.code
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_series.score
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_series.time_length
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private String timeLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table obj_series
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_series.id
     *
     * @return the value of obj_series.id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_series.id
     *
     * @param id the value for obj_series.id
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_series.actor_display
     *
     * @return the value of obj_series.actor_display
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getActorDisplay() {
        return actorDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_series.actor_display
     *
     * @param actorDisplay the value for obj_series.actor_display
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setActorDisplay(String actorDisplay) {
        this.actorDisplay = actorDisplay == null ? null : actorDisplay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_series.definition
     *
     * @return the value of obj_series.definition
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getDefinition() {
        return definition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_series.definition
     *
     * @param definition the value for obj_series.definition
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setDefinition(String definition) {
        this.definition = definition == null ? null : definition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_series.picture_rul1
     *
     * @return the value of obj_series.picture_rul1
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getPictureRul1() {
        return pictureRul1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_series.picture_rul1
     *
     * @param pictureRul1 the value for obj_series.picture_rul1
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setPictureRul1(String pictureRul1) {
        this.pictureRul1 = pictureRul1 == null ? null : pictureRul1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_series.name
     *
     * @return the value of obj_series.name
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_series.name
     *
     * @param name the value for obj_series.name
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_series.language
     *
     * @return the value of obj_series.language
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_series.language
     *
     * @param language the value for obj_series.language
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_series.writer_display
     *
     * @return the value of obj_series.writer_display
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getWriterDisplay() {
        return writerDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_series.writer_display
     *
     * @param writerDisplay the value for obj_series.writer_display
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setWriterDisplay(String writerDisplay) {
        this.writerDisplay = writerDisplay == null ? null : writerDisplay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_series.description
     *
     * @return the value of obj_series.description
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_series.description
     *
     * @param description the value for obj_series.description
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_series.program_type
     *
     * @return the value of obj_series.program_type
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getProgramType() {
        return programType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_series.program_type
     *
     * @param programType the value for obj_series.program_type
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setProgramType(String programType) {
        this.programType = programType == null ? null : programType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_series.program_type2
     *
     * @return the value of obj_series.program_type2
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getProgramType2() {
        return programType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_series.program_type2
     *
     * @param programType2 the value for obj_series.program_type2
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setProgramType2(String programType2) {
        this.programType2 = programType2 == null ? null : programType2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_series.enname
     *
     * @return the value of obj_series.enname
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getEnname() {
        return enname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_series.enname
     *
     * @param enname the value for obj_series.enname
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setEnname(String enname) {
        this.enname = enname == null ? null : enname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_series.release_year
     *
     * @return the value of obj_series.release_year
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getReleaseYear() {
        return releaseYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_series.release_year
     *
     * @param releaseYear the value for obj_series.release_year
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setReleaseYear(String releaseYear) {
        this.releaseYear = releaseYear == null ? null : releaseYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_series.volumn_count
     *
     * @return the value of obj_series.volumn_count
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getVolumnCount() {
        return volumnCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_series.volumn_count
     *
     * @param volumnCount the value for obj_series.volumn_count
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setVolumnCount(String volumnCount) {
        this.volumnCount = volumnCount == null ? null : volumnCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_series.orgair_date
     *
     * @return the value of obj_series.orgair_date
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getOrgairDate() {
        return orgairDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_series.orgair_date
     *
     * @param orgairDate the value for obj_series.orgair_date
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setOrgairDate(String orgairDate) {
        this.orgairDate = orgairDate == null ? null : orgairDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_series.tag
     *
     * @return the value of obj_series.tag
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_series.tag
     *
     * @param tag the value for obj_series.tag
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_series.original_country
     *
     * @return the value of obj_series.original_country
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getOriginalCountry() {
        return originalCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_series.original_country
     *
     * @param originalCountry the value for obj_series.original_country
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setOriginalCountry(String originalCountry) {
        this.originalCountry = originalCountry == null ? null : originalCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_series.is_3d
     *
     * @return the value of obj_series.is_3d
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getIs3d() {
        return is3d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_series.is_3d
     *
     * @param is3d the value for obj_series.is_3d
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setIs3d(String is3d) {
        this.is3d = is3d == null ? null : is3d.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_series.star_level
     *
     * @return the value of obj_series.star_level
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getStarLevel() {
        return starLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_series.star_level
     *
     * @param starLevel the value for obj_series.star_level
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setStarLevel(String starLevel) {
        this.starLevel = starLevel == null ? null : starLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_series.is_charge
     *
     * @return the value of obj_series.is_charge
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getIsCharge() {
        return isCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_series.is_charge
     *
     * @param isCharge the value for obj_series.is_charge
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setIsCharge(String isCharge) {
        this.isCharge = isCharge == null ? null : isCharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_series.chare_desc
     *
     * @return the value of obj_series.chare_desc
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getChareDesc() {
        return chareDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_series.chare_desc
     *
     * @param chareDesc the value for obj_series.chare_desc
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setChareDesc(String chareDesc) {
        this.chareDesc = chareDesc == null ? null : chareDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_series.code
     *
     * @return the value of obj_series.code
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_series.code
     *
     * @param code the value for obj_series.code
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_series.score
     *
     * @return the value of obj_series.score
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_series.score
     *
     * @param score the value for obj_series.score
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_series.time_length
     *
     * @return the value of obj_series.time_length
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public String getTimeLength() {
        return timeLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_series.time_length
     *
     * @param timeLength the value for obj_series.time_length
     *
     * @mbg.generated Thu Dec 13 15:19:45 CST 2018
     */
    public void setTimeLength(String timeLength) {
        this.timeLength = timeLength == null ? null : timeLength.trim();
    }
}